### ISSUE TITLE
菜单错位的问题

### ISSUE THREAD

**Issue by japy93** [LLiuHuan/arco-design-pro-vue#55]
### 问题描述
在布局模式为**左侧菜单混合模式**、左侧菜单为**折叠**状态、语言为**英文**会出现菜单明显的错位的问题；
期望能尽快得到解决，thanks

### 系统信息
操作系统: windows
Node 版本: 19.6.1
包管理器 (npm/yarn/pnpm) 
浏览器：Microsoft Edge 112.0.1722.68 (正式版本) (64 位)

**英文-异常**
<img width="969" alt="英文-异常" src="https://user-images.githubusercontent.com/49198593/236632096-f3593473-7042-4482-8103-9b399506fd27.png">
**中文-正常**
<img width="969" alt="中文-正常" src="https://user-images.githubusercontent.com/49198593/236632105-d68a32b6-1327-4c71-91c4-37b0e8b925c7.png">

**Comment by LLiuHuan** [comment]
收到，非常感谢。这个问题会晚一些解决，最近比较忙，等忙完重构的时候会一起解决。

**Comment by LLiuHuan** [comment]
我明天看一下吧，要是好解决就先解决了，哈哈哈
